var vYear = "2015";
var deviceGPS="Android_Location";if(navigator.userAgent.match(/iPhone/)){deviceGPS="iPhone_Location";}
var facilityDetailPage="facility-screen.htm";var facilityListPage="results-list.htm";var facilityMapPage="results-map.htm";var filterPage="filter-screen.htm";var homePage="home-screen.htm";var facilityInfoTmpl=$.templates("#facilityInformation");var facilityListTmpl=$.templates("#facListTemplate");var stateListTmpl=$.templates("#stateListTemplate");var sectorListTmpl=$.templates("#sectorListTmpl");var stateFilterTmpl=$.templates("#stateListTmpl");var passedData=null;var prevRequest="";var facilitiesList=new Array();var states="";var curFacilityId=null;var userLocation;var isSharingLocation=false;var curStateCode="";var stateList;var sectorsObj;var PAN_TO_USER=0;var PAN_TO_STATE=1;var PAN_TO_FACILITY=2;var PAN_TO_BESTFIT=3;var mapAction=0;var HOMEPAGE="homeScreen";var RESULTS_LIST="ResultsList";var RESULTS_MAP="ResultsMap";var FACILITY_INFO="facilityScreen";var FILTER="filterScreen";var prevPageId=HOMEPAGE;var requestObj={gases:{g1:1,g2:1,g3:1,g4:1,g5:1,g6:1},sectors:{s1:1,s2:1,s3:1,s4:1,s5:1,s6:1,s7:1,s8:1,s9:1},eRange:{lowE:0,highE:23000000},options:{st:"US",q:"",fc:"",sc:0,so:0,ds:'E',pg:0,ry:vYear}};function updateFiltersToRq(){$.each(requestObj.gases,function(idx,obj){$("#"+idx).attr("checked",obj==1?true:false).checkboxradio("refresh");});$.each(requestObj.sectors,function(idx,obj){$("#"+idx).attr("checked",obj==1?true:false).checkboxradio("refresh");});$("#stateMenu").val(requestObj.options.st).selectmenu("refresh");$("#emission_slider_min").val(requestObj.eRange.lowE).slider("refresh");$("#emission_slider_max").val(requestObj.eRange.highE).slider("refresh");}
function resetRQObj(){requestObj={gases:{g1:1,g2:1,g3:1,g4:1,g5:1,g6:1},sectors:{s1:1,s2:1,s3:1,s4:1,s5:1,s6:1,s7:1,s8:1,s9:1},eRange:{lowE:0,highE:23000000},options:{st:"US",q:"",fc:"",sc:0,so:0,ds:'E',pg:0}};}
function buildRequest(svcCall,year){var action="service/";if(!year)
year=vYear;if(svcCall)
action+=svcCall+"/"+year+"?";else
action="service/facilityList/"+vYear+"?";prevRequest=svcCall;action+=$.param(requestObj.eRange);action+="&"+$.param(requestObj.gases);action+="&"+$.param(requestObj.sectors);action+="&"+$.param(requestObj.options);if(prevRequest=="facilitiesWithin"){action+="&lt="+mCenter.latitude+"&ln="+mCenter.longitude;sw=new Microsoft.Maps.Location(bMap.getBounds().getSouth(),bMap.getBounds().getWest());ne=new Microsoft.Maps.Location(bMap.getBounds().getNorth(),bMap.getBounds().getEast());action+="&swlt="+sw.latitude+"&swln="+sw.longitude;action+="&nelt="+ne.latitude+"&neln="+ne.longitude;}
return action;}
var ghgpUrl="http://ghgdata.epa.gov/ghgp/main.do";var twtHT="epa,ghgdata";var socialUrls={"facebook":"http://www.facebook.com/sharer/sharer.php?u="+encodeURIComponent(ghgpUrl),"googlePlus":"https://m.google.com/app/plus/x/?v=compose&content=EPA+GHGP+Data+Publication+tool+"+encodeURIComponent(ghgpUrl),"twitter":"https://twitter.com/intent/tweet?text=EPA+GHGP+Data+Publication+tool+"+encodeURIComponent(ghgpUrl)+"+&hashtags="+twtHT,"reddit":"http://i.reddit.com/submit?url="+encodeURIComponent(ghgpUrl)+"&title=EPA+GHGP+Data+Publication+tool"};function postToTwitter(){window.open(socialUrls.twitter,"_blank");}
function postToFacebook(){window.open(socialUrls.facebook,"_blank");}
function postToGooglePlus(){window.open(socialUrls.googlePlus,"_blank");}
function postToReddit(){window.open(socialUrls.reddit,"_blank");}
$(document).on("pagechange",onPageChange);$(document).on('pageshow','#ResultsMap',resizeMap);$(window).on('orientationchange',resizeMap);$(document).bind("mobileinit",function(){$.support.touchOverflow=true;$.mobile.touchOverflowEnabled=true;$.mobile.defaultPageTransition='none';$.mobile.selectmenu.prototype.options.nativeMenu=true;$.mobile.loading('hide').ajaxStart(function(){$.mobile.loading('show',{theme:"b"});}).ajaxStop(function(){$.mobile.loading('hide');});});function sortByFacName(){curStateCode=$("#selectStateMenu option:selected").val();var upDown=requestObj.options.so==1?0:1;requestObj.options.so=upDown;var request=buildRequest();$.getJSON(request,function(facilities){$.each(facilities,function(i,facility){facility.emissions=addCommas(facility.emissions);});facilitiesList=facilities;$.mobile.changePage('results-list.htm',{type:'GET',data:{prevPage:'HomeScreen',selectedState:curStateCode}});});}
function resizeMap(event){if($.mobile.activePage[0].id==RESULTS_MAP){$("#ResultsMap").height($(window).height()-44-59);$("#map_content").height($(window).height()-44-59);}}
function search(event){var searchQuery=$("#"+this.id+" #searchFacilities").val();requestObj.options.q=searchQuery;var serviceCall=buildRequest("facilityList",vYear);$.getJSON(serviceCall,function(matchingFacilities){$.each(matchingFacilities,function(i,facility){facility.emissions=addCommas(facility.emissions);});facilitiesList=matchingFacilities;if($.mobile.activePage.attr('id')=="ResultsList")
$("#facList").html($("#facListTemplate").render(facilitiesList)).listview("refresh");else
$.mobile.changePage('results-list.htm');});return false;}
function onPageChange(event,data){var toPageId=data.toPage.attr("id");if(toPageId!=RESULTS_LIST)
pagingEnabled=false;if(data.options.fromPage)
prevPageId=data.options.fromPage.attr("id");switch(toPageId){case HOMEPAGE:changeToHomePage(data);break;case RESULTS_LIST:changeToResultsPage(data);break;case RESULTS_MAP:changeToMap(data);break;case FACILITY_INFO:renderFacilityDetails(data);break;case FILTER:if(prevPageId!="stateMenu-dialog")
renderFilterPage(data);break;}
$.mobile.loading('hide');}
function changeToHomePage(data){if(data.options.fromPage&&data.options.fromPage.attr("id")!=""&&data.options.fromPage.attr("id")!="selectStateMenu-dialog"){resetRQObj();curStateCode="";$('#selectStateMenu option').removeAttr('selected');$("#selectStateMenu").selectmenu('refresh',true);}}
function changeToResultsPage(data){if(data.options.data&&data.options.data.selectedState!=curStateCode){curStateCode=data.options.data.selectedState;prevRequest="service/facilityList/"+vYear+"?q=&lowE=0&highE=23000000&fc=&st="+curStateCode+"&pg=0&g1=1&g2=1&g3=1&g4=1&g5=1"+"&g6=1&g7=1&g8=1&g9=1&g10=1&s1=1&s2=1&s3=1&s4=1&s5=1&s6=1&s7=1&s8=1&s9=1&s10=1&ds=E&sc=0&so=0";$.getJSON(prevRequest,function(data){$.each(data,function(i,facility){facility.emissions=addCommas(facility.emissions);});$("#facList").html($("#facListTemplate").render(data)).listview("refresh");facilitiesList=data;});}
else{$("#facList").html($("#facListTemplate").render(facilitiesList)).listview("refresh");}
if(prevPageId!=RESULTS_MAP)
pagingEnabled=true;}
function changeToMap(data){removePinsOutOfBounds(null);switch(mapAction){case PAN_TO_USER:if(userLocation){setVectorPosition(userLocation);displayUserPin();}
break;case PAN_TO_STATE:if(curStateCode){var stateAbbrev=curStateCode;$.getJSON('service/getStateBounds/'+stateAbbrev,function(bounds){var boundary=Microsoft.Maps.LocationRect.fromEdges(bounds['ne']['lat'],bounds['sw']['lng'],bounds['sw']['lat'],bounds['ne']['lng']);bMap.setView({bounds:boundary});mCenter=boundary.center;});}
else{console.log("No State selected, panning to best view of currently selected facilities.");coordinates=[];$.each(facilitiesList,function(i,facility){var latLng=new Microsoft.Maps.Location(facility.latitude,facility.longitude);coordinates.push(latLng);});if(coordinates.length!=0){var bestview=Microsoft.Maps.LocationRect.fromLocations(coordinates);bMap.setView({bounds:bestview});}}
break;case PAN_TO_FACILITY:if(curFacilityId){$.getJSON("service/facilitiesInfo/"+vYear+"?id="+curFacilityId+"&ds=E&et=",function(facilityInfo){setCoordsPosition(facilityInfo.facility.latitude,facilityInfo.facility.longitude);bMap.setView({zoom:14});});}
break;}}
function renderFacilityDetails(data){var facId=0;if(data.options.data&&data.options.data.facilityId!=null)
facId=data.options.data.facilityId;else if(curFacilityId)
facId=curFacilityId;$.getJSON("service/facilitiesInfo/"+vYear+"?id="+facId+"&ds=E&et=",function(facility){facility.totalEmissions=addCommas(facility.totalEmissions);if(facility.gasEmissions[0])
facility.gasEmissions[0].quantity=addCommas(facility.gasEmissions[0].quantity);if(facility.gasEmissions[1])
facility.gasEmissions[1].quantity=addCommas(facility.gasEmissions[1].quantity);if(facility.gasEmissions[2])
facility.gasEmissions[2].quantity=addCommas(facility.gasEmissions[2].quantity);$("#facilityInfoContainer").html($("#facilityInformation").render(facility));});}
function renderFilterPage(data){var fromId=data.options.fromPage[0].id;var toId=data.toPage[0].id;if(fromId&&fromId!=toId)
updateFiltersToRq();}
function generateSectors(){var sectorStr='';if(sectorsObj==null){sectorStr='s1=1&s2=1&s3=1&s4=1&s5=1&s6=1&s7=1&s8=1&s9=1&s10=1&';}
else{sectorsObj.each(function(){sectorStr=sectorStr+'&'+$(this).id+'=';if($(this).on)
sectorStr=sectorStr+'1';else
sectorStr=sectorStr+'0';});}
return sectorStr;}
function getFacilitiesByState(){curStateCode=$("#selectStateMenu option:selected").val();resetRQObj();requestObj.options.st=curStateCode;var request=buildRequest();$.getJSON(request,function(facilities){$.each(facilities,function(i,facility){facility.emissions=addCommas(facility.emissions);});facilitiesList=facilities;mapAction=PAN_TO_STATE;$.mobile.changePage('results-list.htm',{type:'GET',data:{prevPageId:HOMEPAGE,selectedState:requestObj.options.st}});});}
$(document).on('pageinit','#homeScreen',function(event){$(".j-mobileShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeIn(500);});$(".closeShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeOut(500);});$("#searchForm-HP").submit(search);$.getJSON("service/states",function(data){stateList=data;$("#selectStateMenu").html($("#stateListTemplate").render(stateList)).selectmenu('refresh',true);});$('#selectStateMenu',$.mobile.activePage).change(getFacilitiesByState);$("#nearMeBtn").on('tap',initiate_geolocation);$('.homeLogo').on('tap',function(event){$.mobile.changePage("home-screen.htm");});$("#selectStateLink").on('tap',function(e){$('#selectStateMenu-button').trigger('click');});});var pagingEnabled=false;$(window).bind('scroll',function(){if(pagingEnabled){if($.mobile.activePage&&facilitiesList.length>0&&$.mobile.activePage.attr('id')=="ResultsList"&&($(this).scrollTop()+$(this).height())>=($(document).height()-100)){$("#loadingImg").show();$("#loadMoreText").hide();pagingEnabled=false;var nextPage=parseInt(requestObj.options.pg,10)+1;requestObj.options.pg=nextPage;var request=buildRequest(prevRequest);$.getJSON(request,function(data){$.each(data,function(i,facility){facility.emissions=addCommas(facility.emissions);});$("#facList").append($("#facListTemplate").render(data)).listview("refresh");facilitiesList=facilitiesList.concat(data);pagingEnabled=true;if(facilitiesList.length==0){$("#loadMoreText").hide();$("#noResultsFounds").show();pagingEnabled=false;}
else if(data.length<9){$("#loadMoreText").hide();$("#noResultsFounds").hide();pagingEnabled=false;}
else
$("#loadMoreText").show();$("#loadingImg").hide();});}}});var originalChangePage=$.mobile.changePage;$(document).on('pageinit','#ResultsList',function(event){$(".j-mobileShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeIn(500);});$(".closeShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeOut(500);});$('.homeLogo').on('tap',function(event){$.mobile.changePage("home-screen.htm");});$("#searchForm-RL").submit(search);$("#ResultsList li a#map_btn").on('tap',function(event){event.preventDefault();$.mobile.changePage("results-map.htm");return false;});$("li a[href='filter.htm']").on('tap',function(event){event.preventDefault();$.mobile.changePage("filter.htm",{type:"GET",data:{prevPageId:RESULTS_LIST,selectedState:curStateCode}});return false;});$('#facList').on('tap','a',function(event){event.preventDefault();curFacilityId=$(this).attr("id");$.mobile.changePage(facilityDetailPage,{data:{prevPageId:RESULTS_LIST,facilityId:curFacilityId}});return false;});});$(document).on('pageinit','#facilityScreen',function(event){$(".j-mobileShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeIn(500);});$(".closeShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeOut(500);});$('.homeLogo').on('tap',function(event){$.mobile.changePage("home-screen.htm");});$("#searchForm-FD").submit(search);$("#facilityScreen li a[href='filter.htm']").on('tap',function(event){event.preventDefault();var facId=getParameterByName('facilityId');$.mobile.changePage("filter.htm",{type:"GET",data:{prevPageId:FACILITY_INFO,facilityId:facId}});return false;});$("#facilityScreen li a[href='results-map.htm']").on('tap',function(event){event.preventDefault();curFacilityId=getParameterByName('facilityId');var facility=getFacilityById(curFacilityId);mapAction=PAN_TO_FACILITY;$.mobile.changePage("results-map.htm");return false;});});var originalSerializeArray=$.fn.serializeArray;$.fn.extend({serializeArray:function(){var brokenSerialization=originalSerializeArray.apply(this);var checkboxValues=$(this).find('input[type=checkbox]').map(function(){return{'name':this.name,'value':this.checked?'1':'0'};}).get();var checkboxKeys=$.map(checkboxValues,function(element){return element.name;});var withoutCheckboxes=$.grep(brokenSerialization,function(element){return $.inArray(element.name,checkboxKeys)==-1;});return $.merge(withoutCheckboxes,checkboxValues);}});$.fn.digits=function(){return this.each(function(){$(this).text($(this).text().replace(/(\d)(?=(\d\d\d)+(?!\d))/g,"$1,"));});};function generateQuery(formDiv){var formData=formDiv.serializeArray();return formData;}
function hideAllDivsExcept(divName){$("#filterForm  .menuSection").hide();$('[data-role="navbar"] ul li a').removeClass("ui-btn-active");$(divName).show();$('[data-role="navbar"] ul li'+divName+'Link a').addClass("ui-btn-active");}
$(document).on('pageinit','#filterScreen',function(){$('.homeLogo').on('tap',function(event){$.mobile.changePage("home-screen.htm");});$(".j-mobileShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeIn(500);});$(".closeShare").on('tap',function(l){l.preventDefault();$(".mobileShare").fadeOut(500);});if(stateList!=null){$("#stateMenu").html($("#stateListTmpl").render(stateList)).selectmenu('refresh',true);}
else{$.getJSON("service/states",function(data){$("#stateMenu").html($("#stateListTmpl").render(data)).selectmenu('refresh',true);});}
$.getJSON('mobile/json-data/sectorList.json',function(sectorsList){$("#sectorFilter fieldset:jqmData(role='controlgroup')").append($("#sectorListTmpl").render(sectorsList));$("#sectorFilter fieldset:jqmData(role='controlgroup')").trigger("create");$("#sectorFilter fieldset:jqmData(role='controlgroup')").controlgroup("refresh");});$.getJSON("mobile/json-data/gasList.json",function(gases){$("#ghgFilter fieldset:jqmData(role='controlgroup')").html($("#ghgListTmpl").render(gases));$("#ghgFilter fieldset:jqmData(role='controlgroup')").trigger("create");$("#ghgFilter fieldset:jqmData(role='controlgroup')").controlgroup("refresh");});$('#sectorFilterLink').on('tap',function(){hideAllDivsExcept('#sectorFilter');$("#sectorFilter fieldset:jqmData(role='controlgroup')").controlgroup("refresh");});$('#stateFilterLink').on('tap',function(){hideAllDivsExcept('#stateFilter');});$('#ghgFilterLink').on('tap',function(){hideAllDivsExcept('#ghgFilter');$("#ghgFilter fieldset:jqmData(role='controlgroup')").controlgroup("refresh");});$('#emissionFilterLink').on('tap',function(){hideAllDivsExcept('#emissionRangeFilter');});$('#emission_slider_min').change(function(){var min=parseInt($(this).val());var max=parseInt($('#emission_slider_max').val());if(min>max-4000000){$(this).val(max-4000000);$(this).slider('refresh');}
$('#rangeValues').html($('#emission_slider_min').val()+' - '+$('#emission_slider_max').val());});$('#emission_slider_max').change(function(){var min=parseInt($('#emission_slider_min').val());var max=parseInt($(this).val());if(min+4000000>max){$(this).val(min+4000000);$(this).slider('refresh');}
$('#rangeValues').html($('#emission_slider_min').val()+' - '+$('#emission_slider_max').val());});$('#saveBtn').on('tap',function(){var formData=$("#filterForm").serializeArray();